server:
  port: 8081

alarh:
  source:
    path: source.txt
  search:
    startDate: 2021-12-01T00:00:00Z
    endDate: 2021-12-31T00:00:00Z
    resultLimit: 100
    startPosition: 0

logging:
  level:
    ru.alarh.*: debug
